language:
  python

python:
  - "2.6"
  - "2.7"
  - "3.3"

branches:
  only:
    - master

# Install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r requirements.txt --quiet
  - pip install coverage --quiet
  - pip install coveralls --quiet

# Run automated tests with coverage
script:
  - export PYTHONPATH=. && coverage run --source=flask_user flask_user/tests/run_tests.py
  - coverage report -m

# Upload coverage data to coveralls
after_success:
  coveralls

